import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
// import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ["latin"] });
import Dashboard from "./dashboard";
import { useState } from "react";
// import "@/styles/globals.css";
import type { AppProps } from "next/app";
// import "../assets/scss/theme.scss";
import { Provider } from "react-redux";
import { configureStore } from "@reduxjs/toolkit";
import rootReducer from "@/slices";
import { BrowserRouter } from "react-router-dom";
// import dynamic from "next/dynamic";
import dynamic from "next/dynamic";
// const route11 = dynamic(() => import("react-router-dom").then((mod) => mod.BrowserRouter), {
// ssr: false
// });

const store = configureStore({ reducer: rootReducer, devTools: true });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard />
    </>
  );
}
